# Generated by Django 4.2.3 on 2023-08-28 15:11

import Rent_Car.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(upload_to=Rent_Car.models.upload_to)),
                ('doors', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('available_date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent_Car.city')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('dropoff_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='Rent_Car.city')),
                ('rental_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='Rent_Car.city')),
                ('rented_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Rent_Car.car')),
            ],
        ),
    ]
